In [58]:
import numpy as np
import gym
import random

In [93]:
env = gym.make('FrozenLake-v1', desc=None, map_name="4x4", is_slippery = False)

In [110]:
action_space_size = env.action_space.n #4 actions
state_space_size = env.observation_space.n #16 States

qtable = np.zeros((state_space_size,action_space_size)) #ROWS,COLUMNS
qtable

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [111]:
total_episodes = 10000 #no.of times agent plays game
learning_rate = 0.2 #Alpha
max_steps = 100 #loop terminates after 100 steps
gamma = 0.9 #Discount Factor

epsilon = 1 #explore or exploit
max_epsilon = 1
min_epsilon = 0.01
decay_rate = 0.001

In [101]:
#  def converged(qtable):
#      if (list_qtable[-1] - (sum(list_qtable[-5:-1])/5)      #Calculate Percentage difference between matrices to
#                  / (sum(list_qtable[-5:-1])/5)) < 0.001: #Check for convergence,where change in q-table values minimum(<0.001 or 0.1%)
#          return True
#      else: 
#          return False
#  
# list_qtable = []
rewards = []

for episode in range(total_episodes):
    state, n = env.reset() #initialise the env
    step = 0
    done = False
    total_rewards = 0
    for step in range(max_steps):
        
        if random.uniform(0,1) > epsilon:
            action = np.argmax(qtable[state,:]) # Exploit #get the maximum value of actions from the state row
        else:
            action = env.action_space.sample() # Explore
            
        new_state, reward, done, truncated , info = env.step(action) #Gym provies new state in this function


        max_new_state = np.max(qtable[new_state,:]) 
        
        qtable[state,action] = qtable[state,action] + learning_rate*(reward+gamma*max_new_state-qtable[state,action])
        total_rewards += reward
        
        state = new_state
        if done:
            break
            
    # list_qtable.append(qtable)        
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)
    rewards.append(total_rewards)

#     if converged(qtable):
#         break
    
print("Score:", str(sum(rewards)/total_episodes))
print(qtable)

Score: 0.8803
[[0.531441   0.59049    0.59049    0.531441  ]
 [0.531441   0.         0.6561     0.59049   ]
 [0.59049    0.729      0.59049    0.6561    ]
 [0.6561     0.         0.59042529 0.59046225]
 [0.59049    0.6561     0.         0.531441  ]
 [0.         0.         0.         0.        ]
 [0.         0.81       0.         0.6561    ]
 [0.         0.         0.         0.        ]
 [0.6561     0.         0.729      0.59049   ]
 [0.6561     0.81       0.81       0.        ]
 [0.729      0.9        0.         0.729     ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.81       0.9        0.729     ]
 [0.81       0.9        1.         0.81      ]
 [0.         0.         0.         0.        ]]


Sarsa

In [112]:
rewards = []

for episode in range(total_episodes):
    state, n = env.reset() #initialise the env
    step = 0
    done = False
    total_rewards = 0
    for step in range(max_steps):
        
        if random.uniform(0,1) > epsilon: # Max Action
            action = np.argmax(qtable[state,:]) # Exploit #get the maximum value of actions from the state row
        else:
            action = env.action_space.sample() # Explore
            
        new_state, reward, done, truncated , info = env.step(action) #Gym provies new state in this function

        if random.uniform(0,1) > epsilon: # New_Action
            new_action = np.argmax(qtable[new_state,:]) # Exploit #get the maximum value of actions from the state row
        else:
            new_action = env.action_space.sample() # Explore

        SARSA_new_state = qtable[new_state,new_action]
        
        qtable[state,action] = qtable[state,action] + learning_rate*(reward+gamma*SARSA_new_state-qtable[state,action])
        total_rewards += reward
        
        state = new_state
        if done:
            break
            
    # list_qtable.append(qtable)        
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)
    rewards.append(total_rewards)

#     if converged(qtable):
#         break
    
print("Score:", str(sum(rewards)/total_episodes))
print(qtable)

Score: 0.8761
[[0.48265676 0.46212176 0.5904112  0.48702526]
 [0.50767448 0.         0.65607973 0.5109884 ]
 [0.51713088 0.72899652 0.50335974 0.51542758]
 [0.53953866 0.         0.12865984 0.17513263]
 [0.39995777 0.38346984 0.         0.52526137]
 [0.         0.         0.         0.        ]
 [0.         0.8099997  0.         0.64518636]
 [0.         0.         0.         0.        ]
 [0.46495995 0.         0.49244281 0.46587264]
 [0.5624297  0.80848461 0.65463171 0.        ]
 [0.72623299 0.9        0.         0.72510451]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.78242783 0.8997924  0.65936748]
 [0.80780367 0.89999826 1.         0.80699268]
 [0.         0.         0.         0.        ]]


In [103]:
env.reset()

for episode in range(6):
    state,n = env.reset()
    step = 0
    done = False
    
    print("Episode:", episode+1)
    
    for step in range(max_steps):
        action = np.argmax(qtable[state,:])
        new_state, reward, done, truncated , info = env.step(action)
        env.render()
        if done:
            
            print("Number of Steps:", step)
            break
        state = new_state
        
env.close()
        


Episode: 1
Number of Steps: 5
Episode: 2
Number of Steps: 5
Episode: 3
Number of Steps: 5
Episode: 4
Number of Steps: 5
Episode: 5
Number of Steps: 5
Episode: 6
Number of Steps: 5
