The fundamental data type in MxNet is the `ndarray`. This is an n-dimensional-array, or a tensor. If you are familiar with numpy, it has a similar API, and can be converted back and forth from numpy.

The advantage of MxNet over Numpy starts to show up when we are doing deep learning -- GPUs and automatic differentiation support.

In [1]:
from mxnet import nd

/opt/conda/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


Allocating an empty array. This will almost certain come back with 'random' values as it just points at a bit of your memory and allocates it as an array.

In [5]:
nd.empty((3,4))


[[3.7018757e+00 4.5892525e-41 1.1158630e+01 3.0940670e-41]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]]
<NDArray 3x4 @cpu(0)>

You can do normal matrix math if you are familiar, and Numpy style broadcasting, where a smaller *kernel* array is tiled by the operation over a larger array.

In [7]:
nd.ones((3,4)) + nd.ones((3,4))


[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
<NDArray 3x4 @cpu(0)>

In [10]:
nd.ones((3,4)) + 2


[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]
<NDArray 3x4 @cpu(0)>

And you can pick out values with slicing and indexes, with a zero based index scheme, including slicing.

In [16]:
nd.ones((3,4))[0] # first row


[1. 1. 1. 1.]
<NDArray 4 @cpu(0)>

In [17]:
nd.ones((3,4))[1,:1] # second row, last value


[1.]
<NDArray 1 @cpu(0)>

And you can go back and forth to numpy.

In [23]:
n = nd.ones((2,2)).asnumpy()
print(repr(n))
m = nd.array(n)
print(repr(m))

array([[1., 1.],
       [1., 1.]], dtype=float32)

[[1. 1.]
 [1. 1.]]
<NDArray 2x2 @cpu(0)>


If you can do it with Numpy, you can make it happen with MxNet